config/routes.rb
Demo::Application.routes.draw do
  resources :name_lists  

  root :to => "name_lists#index"  
  get "samples/hello"
  get "samples/bye"

  resources :mdemos

  get "mdemos/hello"

  mount WillFilter::Engine => "/will_filter"

  

   match ':controller(/:action(/:id))(.:format)'
   match 'raji' => "samples#hello"
   
end

app/models/mdemo.rb
class Mdemo < ActiveRecord::Base
  attr_accessible :age, :content, :title
end

app/models/name_list.rb
class NameList < ActiveRecord::Base
  attr_accessible :age, :discription, :dob, :gender, :id, :name
end

app/models/name_list_filter.rb
class  NameListFilter < WillFilter::Filter

  def model_class
    NameList 
  end


  
  def default_filters
    [
     ["Male Only", "male_only"],
     ["Female Only", "female_only"]
    ]
  end
  
  def default_filter_conditions(key)
    return [:gender, :is, "male"] if (key == "male_only")
    return [:gender, :is, "Female"] if (key == "female_only")   
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mdemos_controller.rb
class MdemosController < ApplicationController
  # GET /mdemos
  # GET /mdemos.json
  def hello
    render('hello')
  end  
  def index
    @mdemos = Mdemo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mdemos }
    end
  end

  # GET /mdemos/1
  # GET /mdemos/1.json
  def show
    @mdemo = Mdemo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mdemo }
    end
  end

  # GET /mdemos/new
  # GET /mdemos/new.json
  def new
    @mdemo = Mdemo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mdemo }
    end
  end

  # GET /mdemos/1/edit
  def edit
    @mdemo = Mdemo.find(params[:id])
  end

  # POST /mdemos
  # POST /mdemos.json
  def create
    @mdemo = Mdemo.new(params[:mdemo])

    respond_to do |format|
      if @mdemo.save
        format.html { redirect_to @mdemo, notice: 'Mdemo was successfully created.' }
        format.json { render json: @mdemo, status: :created, location: @mdemo }
      else
        format.html { render action: "new" }
        format.json { render json: @mdemo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mdemos/1
  # PUT /mdemos/1.json
  def update
    @mdemo = Mdemo.find(params[:id])

    respond_to do |format|
      if @mdemo.update_attributes(params[:mdemo])
        format.html { redirect_to @mdemo, notice: 'Mdemo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mdemo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mdemos/1
  # DELETE /mdemos/1.json
  def destroy
    @mdemo = Mdemo.find(params[:id])
    @mdemo.destroy

    respond_to do |format|
      format.html { redirect_to mdemos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/name_lists_controller.rb
class NameListsController < ApplicationController
  # GET /name_lists
  # GET /name_lists.json
  def index
    @name_lists = NameList.filter(:params => params, :filter => :name_list_filter)

    if params[:name_lists]      
      @ids = params[:name_lists]      
      @ids.each do |x|
        namelist = NameList.find(x)
        namelist.destroy        
      end
      respond_to do |format|
        format.html { redirect_to name_lists_url }
        format.json { head :no_content }
      end
    end
  end
  
  # GET /name_lists/1
  # GET /name_lists/1.json
  def show
    @name_list = NameList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @name_list }
    end
  end

  # GET /name_lists/new
  # GET /name_lists/new.json
  def new
    @name_list = NameList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @name_list }
    end
  end

  # GET /name_lists/1/edit
  def edit
    @name_list = NameList.find(params[:id])
  end

  # POST /name_lists
  # POST /name_lists.json
  def create
    @name_list = NameList.new(params[:name_list])

    respond_to do |format|
      if @name_list.save
        format.html { redirect_to @name_list, notice: 'Name list was successfully created.' }
        format.json { render json: @name_list, status: :created, location: @name_list }
      else
        format.html { render action: "new" }
        format.json { render json: @name_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /name_lists/1
  # PUT /name_lists/1.json
  def update
    @name_list = NameList.find(params[:id])

    respond_to do |format|
      if @name_list.update_attributes(params[:name_list])
        format.html { redirect_to @name_list, notice: 'Name list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @name_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /name_lists/1
  # DELETE /name_lists/1.json
  def destroy
    @name_list = NameList.find(params[:id])
    @name_list.destroy

    respond_to do |format|
      format.html { redirect_to name_lists_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  def hello
   render :text => "kannan"
  end
  def bye
   render :text => "byeeeeeeeeeee"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mdemos_helper.rb
module MdemosHelper
end

app/helpers/name_lists_helper.rb
module NameListsHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mdemos/_form.html.erb
<%= form_for(@mdemo) do |f| %>
  <% if @mdemo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mdemo.errors.count, "error") %> prohibited this mdemo from being saved:</h2>

      <ul>
      <% @mdemo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mdemos/edit.html.erb
<h1>Editing mdemo</h1>

<%= render 'form' %>

<%= link_to 'Show', @mdemo %> |
<%= link_to 'Back', mdemos_path %>

app/views/mdemos/index.html.erb
<h1>Listing mdemos</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Title</th>
    <th>Age</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mdemos.each do |mdemo| %>
  <tr>
    <td><%= mdemo.content %></td>
    <td><%= mdemo.title %></td>
    <td><%= mdemo.age %></td>
    <td><%= link_to 'Show', mdemo %></td>
    <td><%= link_to 'Edit', edit_mdemo_path(mdemo) %></td>
    <td><%= link_to 'Destroy', mdemo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mdemo', new_mdemo_path %>

app/views/mdemos/new.html.erb
<h1>New mdemo</h1>

<%= render 'form' %>

<%= link_to 'Back', mdemos_path %>

app/views/mdemos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @mdemo.content %>
</p>

<p>
  <b>Title:</b>
  <%= @mdemo.title %>
</p>

<p>
  <b>Age:</b>
  <%= @mdemo.age %>
</p>


<%= link_to 'Edit', edit_mdemo_path(@mdemo) %> |
<%= link_to 'Back', mdemos_path %>

app/views/name_lists/_form.html.erb
<%= form_for(@name_list) do |f| %>
  <% if @name_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@name_list.errors.count, "error") %> prohibited this name_list from being saved:</h2>

      <ul>
      <% @name_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :dob %><br />
    <%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label :discription %><br />
    <%= f.text_area :discription %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/name_lists/edit.html.erb
<h1>Editing name_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @name_list %> |
<%= link_to 'Back', name_lists_path %>

app/views/name_lists/index.html.erb
<%= will_filter_tag(@name_lists) %>
  <%= form_tag('', :id => 'name_lists_form', :method =>"delete") do %>
<%= will_filter_table_tag(@name_lists, :columns => [
                                                    [:checkbox, 'name_lists'], 
                                                    :id, 
                                                    :name,
                                                    :age,
                                                    :gender,
                                                    {:key =>:dob, :title=> "Date OF Birth"},
                                                    
                                                    [:actions, lambda{ |obj|
                                                       actions = []
                                                       actions << link_to('show', :action => :show, :id => obj.id)	
                                                       actions << link_to('edit', :action => :edit, :id => obj.id)	
                                                       actions << link_to( "Delete", name_list_path(obj.id), :method=>"delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) )	
                                                       actions.join(' | ').html_safe
                                                     }, 'padding:3px;width:80px;padding-left:10px;']
                                                   ]) %>
  <%= will_filter_actions_bar_tag(@name_lists, [
                                                ["Delete Selected lists", "
 		if (!confirm('Are you sure you want to delete all selected users?')) return;
 		document.getElementById('name_lists_form').action = '/name_lists'
 		document.getElementById('name_lists_form').submit();	
        "]
                                               ]) %>

<% end %>

app/views/name_lists/new.html.erb
<h1>New name_list</h1>

<%= render 'form' %>

<%= link_to 'Back', name_lists_path %>

app/views/name_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @name_list.id %>
</p>

<p>
  <b>Name:</b>
  <%= @name_list.name %>
</p>

<p>
  <b>Age:</b>
  <%= @name_list.age %>
</p>

<p>
  <b>Gender:</b>
  <%= @name_list.gender %>
</p>

<p>
  <b>Dob:</b>
  <%= @name_list.dob %>
</p>

<p>
  <b>Discription:</b>
  <%= @name_list.discription %>
</p>


<%= link_to 'Edit', edit_name_list_path(@name_list) %> |
<%= link_to 'Back', name_lists_path %>

app/views/samples/hello.html.erb
<h1>Samples#hello</h1>
<p>Find me in app/views/samples/hello.html.erb</p>